# Setup
title:        Long LaMP
tagline:      Personalized Long-Text Generation
baseurl:      "/longLaMPbenchmark.github.io"
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Ishita Kumar, Snigdha Vishwanathan, Sushrita Yerra, Alireza Salemi, Ryan A. Rossi

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown