# Setup
title:        Long LaMP
tagline:      Personalized Long-Text Generation
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Sushrita Yerra #Ishita Kumar, Snigdha Vishwanathan, Sushrita Yerra, Alireza Salemi, Ryan A. Rossi
  url:        https://longlamp-benchmark.github.io/longLaMPbenchmark.github.io/ 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown